<?php
function echo_content($str)
{
	$l=fopen($str,"r");
	$arr=file($str);
	$num=count($arr);
	for($i=0;$i<$num;$i++)
	{
		echo $arr[$i];
	}
	return;
}

echo_content("header.txt");
echo_content("side_full.txt");
?>
 
 <div id="content">
     <h1 id="toptext">Full Throttle</h1> 
<p><img hspace="10" vspace"5" border="0" align="right" src="./img/ft.gif">As the lights turn green, these mean machines blast off. Drive your way to glory with your own little Dragster.</p>
<p>This year, we let you achieve breakneck speeds legally with machines
powered by miniature engines and driven by RC controls.</p>
<p>Set the road ablaze...</p><br>
<a name="prob"></a>	 
<h1>Problem Statement</h1>
<p>Make a remote controlled car that can complete the given distance of 40m on a flat and straight track in the shortest possible time.</p>
<h1>Machine Specifications</h1>
<ul>
<li>The machine should fit within a box of dimensions (80x40x25) cm at any and every given point of the game. The external device which is used to control the machine manually is not included in the size constraint.</li> 
<li>The machine must use only mechanical power generated by an Internal Combustion Engine or mechanical power converted from a source of electrical energy. Compressed gas and rockets are strictly prohibited. </li>
<li>The use of IC engines is strongly recommended to all the contestants for better performance. </li>
<li>Participants can use a maximum of <strong>1.6 cc</strong> IC engine. The voltage anywhere in the machine should <strong>not</strong> be more than 24V at any point of time.</li>
<li>All the machines have to be necessarily controlled by some wireless control mechanism throughout the competition. </li>
<li>The machine must have onboard source of power. External source of power is not allowed. </li>
<li>The machine <strong>must</strong> have two remote control circuits (or dual frequency remote circuit) onboard, which can be switched in between before the start of the race in order to avoid the frequency interference between the participating cars.</li>
<li>The machine should not be made using Lego parts. However the remote control systems from toys can be used. </li>
<li>All the participants using IC engines, in order to control the <strong>START</strong> of their car during the race after starting the IC engine must use either clutch system in their machine or use some other mechanism such as a stand (launching pad) which will lift the wheels coupled to the engine and which can be dropped easily either by some <strong>trigger</strong> or by remote control when the car is required to <strong>START OFF</strong> after the light turns green. Due to the complications involved in introducing the clutch system, we suggest use of the later mechanism or any other mechanism one can come up with.</li>
<li>The size of the launch pad is not included in the given size constraint for the car.   </li>  
<li>IC engine installed on the car can be started by any mechanism before the green light but the car must not leave the starting line before the green flag is set. Doing so will lead to disqualification.</li>
<li>The participants must device some mechanism for the engine to stop running after the race is completed.</li>
</ul>
<a name="arena"></a>
<h1>Arena</h1>
<ul>
<li>The race will be carried out on a hardened clay straight track</li>.
<li>The track is 40m long and 4m wide (2m for each of the competing team).</li>
<li>After the finish line, slow down track of 30 m will be provided for the machines to come to a halt.</li>
</ul>
<a name="grules"></a>
<h1>Game Rules</h1>
<ul>
<li>The tournament will be played on a knockout basis with two teams competing against each other at a time.</li>
<li>The team which finishes first will be declared the winner and move on to the next round.</li>
<li>At the beginning of the game, teams have to place their machine at their respective starting line. Before the start of the run, all parts of the machine should be behind the starting line. </li>
<li>The machine should not leave the given arena at any point of time during a race. Doing so will lead to disqualification.</li>
<li>The machine must not enter in the opponent's part of the arena. Doing so will lead to disqualification from the game. </li>
<li>The machine should not remain stationary for more than 10 sec. on the track after the green light, otherwise it will be disqualified.</li>
<li>If the car does not complete the race in 20 sec. it will lead to disqualification.</li>
<li>If any of the machines starts off before the green light is set, then the race will start again but if second time, any of the machines starts before green light then that machines will be disqualified. <strong>NO RE-MATCH</strong> will be held second time. </li>
</ul>
<a name="gnrules"></a>
<h1>General rules</h1>
<ul>
<li>Every team has to register online at our website for the competition. The Registration starts from <strong>1st September 2005</strong>. A registration number will be allocated to the team on registration which shall be used for future reference.</li> 
<li>Each team can have a maximum of 4 team members.</li>
<li>Team members are not permitted to touch either their machines or those of their opponents once the game begins. The penalty for doing so is disqualification. </li>
<li>The cars are not allowed to dismember themselves or leave parts on any part of the arena. </li>
<li>Any team that is not ready to play at the time specified will be scratched from the competition automatically.</li> 
<li>The structure of the qualification round and rest of the competition will be announced at a later date.</li>
<li>Machines will have to be demonstrated to judges (who will evaluate the machines for other prizes) at a time and date specified in the schedule which will be put up. Any team that does not turn up at the specified time will not be considered for the above special prizes.</li> 
<li>The machine would be checked for its safety before the race and would be discarded if found unsafe for other participants and spectators.</li>
<li>The teams must adhere to the spirit of healthy competition. The teams must not damage the opponent's machine in any way. Judges reserve the right to disqualify any team indulged in misbehavior. </li>
<li>Judges decision shall be treated as final and binding on all.	</li>
<li>The name of your machine must be prominently displayed on the machine.</li>
<li>The organizers reserve all rights to change any or all of the above rules as they deem fit. Change in any rule, if any will be highlighted on the website.</li>
<li>On the request from the participants, supply of IC engine will be arranged, on payment of the required amount.</li>



</li>

</ul>
<a name="elig"></a>
<h1 id="toptext">Eligibility</h1> 
<p>All students with a valid identity card of their respective educational institutes are eligible to participate in Full Throttle at Techfest 2006.</p> 
<br>
<p>A Few useful links for participants:</p>
<a href="http://www.rcdrags.com" target="_blank">http://www.rcdrags.com</a><br>
<a href="http://www.howstuffworks.com" target="_blank" >http://www.howstuffworks.com</a>

<br><br>For queries contact:<br>
<table border="0" align="left" id="manag"  style="border-collapse:collapse; " width="100%">
<tr><td width="20%">Amardeep<br>
Manager, Sixth Gear<br>
<a href="http://www.techfest.org/mail.php?email=amar@techfest.org" target="_blank">amar@techfest.org</a><br>
Ph. +91-93233 95608<br></td>
<td>Aditya Chaoji<br>
Manager, Sixth Gear<br>
<a href="http://www.techfest.org/mail.php?email=aditya@techfest.org" target="_blank">aditya@techfest.org</a><br>
Ph. +91-98693 57291<br></td>
</tr>
</table>

<br><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


</div>
  
<?

echo_content("footer.txt");
?>