<?php
function echo_content($str)
{
	$l=fopen($str,"r");
	$arr=file($str);
	$num=count($arr);
	for($i=0;$i<$num;$i++)
	{
		echo $arr[$i];
	}
	return;
}
echo_content("header.txt");
echo_content("side_no.txt");
?>
<!-- ##### Main Copy ##### -->

    <div id="content">
     <h1 id="toptext">Feedback Techfest 2005</h1> 
	 <?
$dbhost = '70.85.134.18';   
$dbname = 'techfest';
$dbuser = 'techfest';
$dbpasswd = 'tec45st';
        
$link = mysql_connect($dbhost,$dbuser,$dbpasswd)
or die("Could not connect : " . mysql_error());
mysql_select_db($dbname) or die("Query failed : " . mysql_error());
echo "<h3>How did you come to know about Techfest</h3><br>";

echo '<table align="left" width="100%" style="border-collapse:collapse ">';
echo "<tr><td width='25%'>Web Search: ";
$query="SELECT * FROM feedback WHERE howtech=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Friends: ";
$query="SELECT * FROM feedback WHERE howtech=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Posters: ";
$query="SELECT * FROM feedback WHERE howtech=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Others: ";
$query="SELECT * FROM feedback WHERE howtech=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr>";
echo "</table>";




echo "<h3>When did you come to know about Techfest?</h3>";
echo '<table align="left" width="100%" style="border-collapse:collapse ">';
echo "<tr><td width='25%'>Before Sep :";
$query="SELECT * FROM feedback WHERE publitime=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Sep-Oct: ";
$query="SELECT * FROM feedback WHERE publitime=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Oct- Nov : ";
$query="SELECT * FROM feedback WHERE publitime=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Dec-Jan: ";
$query="SELECT * FROM feedback WHERE publitime=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr>";
echo "</table>";




echo "<h3>How aware are people around u about Techfest?</h3>";
echo '<table align="left" width="100%" style="border-collapse:collapse ">';
echo "<tr><td width='25%'>Low :";
$query="SELECT * FROM feedback WHERE aware=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Moderate: ";
$query="SELECT * FROM feedback WHERE aware=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Good : ";
$query="SELECT * FROM feedback WHERE aware=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr>";
echo "</table>";



//events
echo "<h3>Did you get enough time to prepare for competitions after you came to know about them?</h3>";
echo '<table align="left" width="110%" style="border-collapse:collapse ">';
echo "<tr><td width='25%'>Got Enough Time :";
$query="SELECT * FROM feedback WHERE enought=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "More time would have been better: ";
$query="SELECT * FROM feedback WHERE enought=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Couldn't participate due to lack of time : ";
$query="SELECT * FROM feedback WHERE enought=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr>";
echo "</table>";




echo "<h3>Learning experience</h3><br>";
echo '<table align="left" width="110%" style="border-collapse:collapse ">';
echo "<tr><td width='9%'>0 :";
$query="SELECT * FROM feedback WHERE learnex=0";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "1 :";
$query="SELECT * FROM feedback WHERE learnex=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "2 :";
$query="SELECT * FROM feedback WHERE learnex=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "3 :";
$query="SELECT * FROM feedback WHERE learnex=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "4 :";
$query="SELECT * FROM feedback WHERE learnex=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "5 :";
$query="SELECT * FROM feedback WHERE learnex=5";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "6 :";
$query="SELECT * FROM feedback WHERE learnex=6";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "7 :";
$query="SELECT * FROM feedback WHERE learnex=7";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "8 :";
$query="SELECT * FROM feedback WHERE learnex=8";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "9 :";
$query="SELECT * FROM feedback WHERE learnex=9";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "10 :";
$query="SELECT * FROM feedback WHERE learnex=10";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr></table>";





echo "<h3>Entertainment</h3>";
echo '<table align="left" width="110%" style="border-collapse:collapse ">';
echo "<tr><td width='9%'>0 :";
$query="SELECT * FROM feedback WHERE entertainment=0";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "1 :";
$query="SELECT * FROM feedback WHERE entertainment=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "2 :";
$query="SELECT * FROM feedback WHERE entertainment=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "3 :";
$query="SELECT * FROM feedback WHERE entertainment=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "4 :";
$query="SELECT * FROM feedback WHERE entertainment=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "5 :";
$query="SELECT * FROM feedback WHERE entertainment=5";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "6 :";
$query="SELECT * FROM feedback WHERE entertainment=6";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "7 :";
$query="SELECT * FROM feedback WHERE entertainment=7";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "8 :";$query="SELECT * FROM feedback WHERE entertainment=8";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "9 :";$query="SELECT * FROM feedback WHERE entertainment=9";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "10 :";
$query="SELECT * FROM feedback WHERE learnex=10";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr></table>";




echo "<h3>Organisation</h3>";
echo '<table align="left" width="110%" style="border-collapse:collapse ">';
echo "<tr><td width='9%'>0 :";
$query="SELECT * FROM feedback WHERE organisation=0";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "1 :";
$query="SELECT * FROM feedback WHERE organisation=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "2 :";
$query="SELECT * FROM feedback WHERE organisation=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "3 :";
$query="SELECT * FROM feedback WHERE organisation=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "4 :";
$query="SELECT * FROM feedback WHERE organisation=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "5 :";$query="SELECT * FROM feedback WHERE organisation=5";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "6 :";$query="SELECT * FROM feedback WHERE organisation=6";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "7 :";$query="SELECT * FROM feedback WHERE organisation=7";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "8 :";$query="SELECT * FROM feedback WHERE organisation=8";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "9 :";$query="SELECT * FROM feedback WHERE organisation=9";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "10 :";
$query="SELECT * FROM feedback WHERE organisation=10";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr></table>";







echo "<h3>Level</h3>";
echo '<table align="left" width="110%" style="border-collapse:collapse ">';
echo "<tr><td width='9%'>0 :";
$query="SELECT * FROM feedback WHERE level=0";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "1 :";
$query="SELECT * FROM feedback WHERE level=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "2 :";
$query="SELECT * FROM feedback WHERE level=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "3 :";
$query="SELECT * FROM feedback WHERE level=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "4 :";
$query="SELECT * FROM feedback WHERE level=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "5 :";$query="SELECT * FROM feedback WHERE level=5";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "6 :";$query="SELECT * FROM feedback WHERE level=6";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "7 :";$query="SELECT * FROM feedback WHERE level=7";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "8 :";$query="SELECT * FROM feedback WHERE level=8";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "9 :";$query="SELECT * FROM feedback WHERE level=9";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "10 :";
$query="SELECT * FROM feedback WHERE level=10";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr></table>";





echo "Canteen<br>";
echo '<table align="left" width="110%" style="border-collapse:collapse ">';
echo "<tr><td width='9%'>0 :";
$query="SELECT * FROM feedback WHERE canteen=0";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "1 :";
$query="SELECT * FROM feedback WHERE canteen=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "2 :";
$query="SELECT * FROM feedback WHERE canteen=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "3 :";
$query="SELECT * FROM feedback WHERE canteen=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "4 :";
$query="SELECT * FROM feedback WHERE canteen=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "5 :";$query="SELECT * FROM feedback WHERE canteen=5";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "6 :";$query="SELECT * FROM feedback WHERE canteen=6";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "7 :";$query="SELECT * FROM feedback WHERE canteen=7";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "8 :";$query="SELECT * FROM feedback WHERE canteen=8";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "9 :";$query="SELECT * FROM feedback WHERE canteen=9";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "10 :";
$query="SELECT * FROM feedback WHERE learnex=10";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr></table>";






echo "Overall<br>";
echo '<table align="left" width="110%" style="border-collapse:collapse ">';
echo "<tr><td width='9%'>0 :";
$query="SELECT * FROM feedback WHERE overall=0";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "1 :";
$query="SELECT * FROM feedback WHERE overall=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "2 :";
$query="SELECT * FROM feedback WHERE overall=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "3 :";
$query="SELECT * FROM feedback WHERE overall=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "4 :";
$query="SELECT * FROM feedback WHERE overall=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "5 :";
$query="SELECT * FROM feedback WHERE overall=5";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "6 :";
$query="SELECT * FROM feedback WHERE overall=6";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "7 :";
$query="SELECT * FROM feedback WHERE overall=7";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "8 :";
$query="SELECT * FROM feedback WHERE overall=8";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='9%'>";
echo "9 :";
$query="SELECT * FROM feedback WHERE overall=9";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='10%'>";
echo "10 :";
$query="SELECT * FROM feedback WHERE overall=10";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr></table>";


echo "<h3>Will you participate again in Techfest in the coming years?</h3>";
echo '<table align="left" width="100%" style="border-collapse:collapse ">';
echo "<tr><td width='25%'>Yes :";
$query="SELECT * FROM feedback WHERE again=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "No: ";
$query="SELECT * FROM feedback WHERE again=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr>";
echo "</table>";

echo "<h3>Do you want problem statement of competitions be made available via post?</h3>";
echo '<table align="left" width="100%" style="border-collapse:collapse ">';
echo "<tr><td width='25%'>Yes, that wud be better :";
$query="SELECT * FROM feedback WHERE viapost=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "No, web is better: ";
$query="SELECT * FROM feedback WHERE viapost=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr>";
echo "</table>";



echo "<h3>Which of the following events are you most inclined to participate in?</h3>";
echo '<table align="left" width="100%" style="border-collapse:collapse ">';
echo "<tr><td width='25%'>Competitions :";
$query="SELECT * FROM feedback WHERE pref=1";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Workshop/lectures: ";
$query="SELECT * FROM feedback WHERE pref=2";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Quizes : ";
$query="SELECT * FROM feedback WHERE pref=3";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td><td width='25%'>";
echo "Other on the spot : ";
$query="SELECT * FROM feedback WHERE pref=4";
$result=mysql_query($query);
echo mysql_error();
$num=mysql_num_rows($result); 
echo $num;
echo "</td></tr>";
echo "</table>";

echo "<br><br></div>";
echo_content("footer.txt");

?>
