<h2>SCHEDULE</h2>
<br>
<TABLE CELLSPACING=0 BORDER=1>		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana">Lecture Series</FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">24, Sat</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="930" SDNUM="1033;"><FONT FACE="Verdana">930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Inauguration</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Prof. Kevin Warwick</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1830" SDNUM="1033;"><FONT FACE="Verdana">1830</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dr. Raghuram Rajan</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT (VC)</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">25, Sun</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Prof. Yash Pal</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dr. Bharat Balasubramanian</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1800" SDNUM="1033;"><FONT FACE="Verdana">1800</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Panel Discussion</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">26, Mon</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1130" SDNUM="1033;"><FONT FACE="Verdana">1130</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dr. Alex Pentland</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT (VC)</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1330" SDNUM="1033;"><FONT FACE="Verdana">1330</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Prof. Yajnik</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana">Competitions</FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">24, Sat</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Open Software</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">?</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Water Rockets (Elims)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gymkhana grounds</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Open Design</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">SOM Foyer</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Krazie Idea</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KreSIT Med 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dirt Racing</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">25, Sun</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Open Hardware</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">SOM Foyer</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Open Software</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">?</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Kurukshetra</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Med 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Water Rockets (Finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gymkhana grounds</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dirt Racing</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">26, Mon</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Contraption</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">SOM Foyer</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Open Software</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">?</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1030" SDNUM="1033;"><FONT FACE="Verdana">1030</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Atlantis</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Med 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Planet Earth</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana">Yantriki</FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">24, Sat</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Yantriki (Qualifying)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">SOM Well</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">25, Sun</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Cliffhanger (Qualifying)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">SOM Well</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">26, Mon</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="900" SDNUM="1033;"><FONT FACE="Verdana">900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">CH, LMS, MM (Buffer)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">SOM Well</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1630" SDNUM="1033;"><FONT FACE="Verdana">1630</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Cliffhanger, LMS, MM (Finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Convo</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana">Last Straw</FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">24, Sat</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="930" SDNUM="1033;"><FONT FACE="Verdana">930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1730" SDNUM="1033;"><FONT FACE="Verdana">1730</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Last Straw (Elims)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Convo Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">25, Sun</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="930" SDNUM="1033;"><FONT FACE="Verdana">930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1730" SDNUM="1033;"><FONT FACE="Verdana">1730</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Last Straw (Finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Convo Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">26, Mon</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1030" SDNUM="1033;"><FONT FACE="Verdana">1030</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Const Mngmnt</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Small 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana">Chemsplash</FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">24, Sat</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Turbulence (Elims)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1900" SDNUM="1033;"><FONT FACE="Verdana">1900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">la porsChe (Elims)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">25, Sun</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="930" SDNUM="1033;"><FONT FACE="Verdana">930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">High Spirits</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">LT Back Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Technum Opus (Making)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Circular Hall</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1900" SDNUM="1033;"><FONT FACE="Verdana">1900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">la porsChe (Finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">26, Mon</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dexter's Den (Finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Convo Foyer</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Technum Opus (Display)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Convo Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana">Workshops</FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">24, Sat</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">GPS</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 3</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1130" SDNUM="1033;"><FONT FACE="Verdana">1130</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gaming </FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IRCC Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">K Rajesh Rao, Dhruva</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Car Tech</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Arora, M&amp;M</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">GPS - H/O</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gymkhana Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">25, Sun</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="930" SDNUM="1033;"><FONT FACE="Verdana">930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IPR</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IRCC Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Prof. Prabudha Ganguly</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Car Tech</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 2</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">H N Subbarao, M&amp;M</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">GIS</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 3</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1030" SDNUM="1033;"><FONT FACE="Verdana">1030</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gaming</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Ashutosh Rege, Nvidia</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IPR (Research)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">CC</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">GIS H/O</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">?</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gaming H/O</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">?</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dhruva</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IPR H/O</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Aero H/O</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">ED Hall</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1730" SDNUM="1033;"><FONT FACE="Verdana">1730</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Car Tech</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 2</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">V R Kulkarni, Fiat</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">-</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Aero (Flying Session)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gymkhana Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">26, Mon</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1130" SDNUM="1033;"><FONT FACE="Verdana">1130</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Car Tech</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 2</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">V M Barve, M&amp;M</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1330" SDNUM="1033;"><FONT FACE="Verdana">1330</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Smart Materials</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 3</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1130" SDNUM="1033;"><FONT FACE="Verdana">1130</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Aero</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 4</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Samson D' Silva, Space Apple</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1130" SDNUM="1033;"><FONT FACE="Verdana">1130</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Aero H/O</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">ED Hall</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1130" SDNUM="1033;"><FONT FACE="Verdana">1130</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gaming</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 1</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Deepak Ail, India Games Ltd</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Aero</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">IC 4</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Samson D' Silva, Space Apple</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Aero H/O</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">ED Hall</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">-</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Aero (Flying Session)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Gymkhana Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana">Hub</FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana"><BR></FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">24, Sat</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1200" SDNUM="1033;"><FONT FACE="Verdana">1200</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Documentary</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1200" SDNUM="1033;"><FONT FACE="Verdana">1200</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">How Stuff Works</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Quiz elims</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Documentary</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Talk (Prof. Shenoy)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Quiz (finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1830" SDNUM="1033;"><FONT FACE="Verdana">1830</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">SciTech</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Convo</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">25, Sun</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Documentary</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Relay - Prof Yash Pal</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">TCS Quiz (Elims)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Documentary</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Tech Talk</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1530" SDNUM="1033;"><FONT FACE="Verdana">1530</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">How Stuff Works</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1600" SDNUM="1033;"><FONT FACE="Verdana">1600</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1700" SDNUM="1033;"><FONT FACE="Verdana">1700</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">TCS Quiz (Finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">26, Mon</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1000" SDNUM="1033;"><FONT FACE="Verdana">1000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Documentary</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1100" SDNUM="1033;"><FONT FACE="Verdana">1100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Airforce</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1230" SDNUM="1033;"><FONT FACE="Verdana">1230</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1300" SDNUM="1033;"><FONT FACE="Verdana">1300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Tech Talk</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1400" SDNUM="1033;"><FONT FACE="Verdana">1400</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1500" SDNUM="1033;"><FONT FACE="Verdana">1500</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Turbulence (Finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">KReSIT Audi</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Verdana">Technoholix</FONT></B></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">24, Sat</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">la porsChe (Elims)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dirt Racing</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Colosseum</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Smart Home</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Walk-Through</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2000" SDNUM="1033;"><FONT FACE="Verdana">2000</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2045" SDNUM="1033;"><FONT FACE="Verdana">2045</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Cako</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">OAT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2300" SDNUM="1033;"><FONT FACE="Verdana">2300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Movie</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">OAT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">25, Sun</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">la porsChe (Finals)</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Dirt Racing</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Walking on Water</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Swimming Pool</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Colosseum</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Smart Home</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Walk-Through</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2300" SDNUM="1033;"><FONT FACE="Verdana">2300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Movie</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">OAT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2300" SDNUM="1033;"><FONT FACE="Verdana">2300</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="30" SDNUM="1033;"><FONT FACE="Verdana">0030</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Winged Migrations</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">OAT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">26, Mon</FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1900" SDNUM="1033;"><FONT FACE="Verdana">1900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Display of Prize Winners</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1900" SDNUM="1033;"><FONT FACE="Verdana">1900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Colosseum</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1900" SDNUM="1033;"><FONT FACE="Verdana">1900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Smart Home</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1900" SDNUM="1033;"><FONT FACE="Verdana">1900</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Walk-Through</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Surbahar Lawns</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="1930" SDNUM="1033;"><FONT FACE="Verdana">1930</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">SciTech</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">OAT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=97 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
			<TD WIDTH=51 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2100" SDNUM="1033;"><FONT FACE="Verdana">2100</FONT></TD>
			<TD WIDTH=53 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM SDVAL="2300" SDNUM="1033;"><FONT FACE="Verdana">2300</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">Movie</FONT></TD>
			<TD WIDTH=120 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana">OAT</FONT></TD>
			<TD WIDTH=175 HEIGHT=18 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Verdana"><BR></FONT></TD>
		</TR>
</TABLE>
<br><br>

